spring:
  kafka:
    # ───────────── Bootstrap & Common ─────────────
    bootstrap-servers: localhost:9092                      # Kafka broker address :contentReference[oaicite:3]{index=3}
    client-id: notification-service                       # Unique client identifier :contentReference[oaicite:4]{index=4}

    # ───────────── Producer Settings ─────────────
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer   # Key → byte[] :contentReference[oaicite:5]{index=5}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # JSON payload :contentReference[oaicite:6]{index=6}
      acks: all                              # Ensure leader+replicas ack before success :contentReference[oaicite:7]{index=7}
      retries: 3                             # Retry on transient failures :contentReference[oaicite:8]{index=8}
      max-in-flight-requests-per-connection: 1  # Prevent reordering on retry :contentReference[oaicite:9]{index=9}
      enable-idempotence: true        # Exactly-once per partition :contentReference[oaicite:10]{index=10}
      # linger.ms: 100                         # Batch small messages (optional) :contentReference[oaicite:11]{index=11}
    # Optional: enable transactions for atomic consume-produce
    template:
      transaction-id-prefix: tx-               # Prefix for transactional producers :contentReference[oaicite:12]{index=12}

    # ───────────── Consumer Settings ─────────────
    consumer:
      group-id: notification-group              # Consumer group for parallelism :contentReference[oaicite:13]{index=13}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer   # Key deserializer :contentReference[oaicite:14]{index=14}
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # JSON deserializer :contentReference[oaicite:15]{index=15}
      auto-offset-reset: earliest               # Start from earliest if no offset :contentReference[oaicite:16]{index=16}
      enable-auto-commit: false                 # Manual ack for control :contentReference[oaicite:17]{index=17}
      max-poll-records: 50                      # Max records per poll (tune to your load) :contentReference[oaicite:18]{index=18}
      isolation-level: read_committed           # Skip uncommitted transactional data :contentReference[oaicite:19]{index=19}

    # ───────────── Additional Common Props ─────────────
    properties:
      # Kafka client internals (tweak these as needed)
      retry.backoff.ms: 200                     # Backoff between retries :contentReference[oaicite:20]{index=20}
      request.timeout.ms: 5000                  # Overall request timeout :contentReference[oaicite:21]{index=21}
